apiVersion: v1
kind: Service
metadata:
  name: aiot-chat
spec:
  selector:
    app: aiot-chat
  ports:
  - protocol: "TCP"
    port: 7860
    targetPort: 7860
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiot-chat
spec:
  selector:
    matchLabels:
      app: aiot-chat
  replicas: 1
  template:
    metadata:
      labels:
        app: aiot-chat
    spec:
      containers:
      - name: aiot-chat
        image: jpjayprasad-dev/aiotchat:latest
        imagePullPolicy: Never
        ports:
          - containerPort: 7860
        env:
          - name: PORTAL_HOST
            valueFrom:
              configMapKeyRef:
                name: bot-variables
                key: PORTAL_HOST
          - name: ES_HOST
            valueFrom:
              configMapKeyRef:
                name: bot-variables
                key: ES_HOST
          - name: OPENAI_KEY
            valueFrom:
              secretKeyRef:
                name: openai-credentials
                key: openai_key
